name: Download Artifact String
description: Download an artifact as a string

inputs:
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
outputs:
  string:
    description: "The contents of the archive"
    value: ${{ steps.output.outputs.string }}

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
    - run: unzip ${{ inputs.path }}
      shell: bash
    - run: |
          OUTPUT=''
          for file in ${{ inputs.path }}/*.yml; do
            echo "Appending $file to string"
            OUTPUT+=$(cat $file)
          done
          echo "::set-output name=string::$OUTPUT"
      id: output
      shell: bash