name: Dependabot Auto Merge
on: pull_request_target

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    uses: actionsaustenstone/.github/.github/workflows/dependabot-auto-merge.yml@v2
