name: Future Run

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '* * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            return artifacts.data[0].name
      - uses: austenstone/austenstone/actions/download-artifact-string@main
        with:
          name: ${{ steps.artifact.outputs.result }}
      - run: echo ${{ steps.download.outputs.string }}